/*
 * This file is generated by jOOQ.
*/
package codes.foobar.wedapp.jooq;


import codes.foobar.wedapp.jooq.tables.Accommodation;
import codes.foobar.wedapp.jooq.tables.Contact;
import codes.foobar.wedapp.jooq.tables.Direction;
import codes.foobar.wedapp.jooq.tables.Guest;
import codes.foobar.wedapp.jooq.tables.IndexPage;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 642348446;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>accommodation</code>.
     */
    public final Accommodation ACCOMMODATION = codes.foobar.wedapp.jooq.tables.Accommodation.ACCOMMODATION;

    /**
     * The table <code>contact</code>.
     */
    public final Contact CONTACT = codes.foobar.wedapp.jooq.tables.Contact.CONTACT;

    /**
     * The table <code>direction</code>.
     */
    public final Direction DIRECTION = codes.foobar.wedapp.jooq.tables.Direction.DIRECTION;

    /**
     * The table <code>guest</code>.
     */
    public final Guest GUEST = codes.foobar.wedapp.jooq.tables.Guest.GUEST;

    /**
     * The table <code>index_page</code>.
     */
    public final IndexPage INDEX_PAGE = codes.foobar.wedapp.jooq.tables.IndexPage.INDEX_PAGE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ACCOMMODATION_ID_SEQ,
            Sequences.CONTACT_ID_SEQ,
            Sequences.DIRECTION_ID_SEQ,
            Sequences.GUEST_ID_SEQ,
            Sequences.INDEX_PAGE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Accommodation.ACCOMMODATION,
            Contact.CONTACT,
            Direction.DIRECTION,
            Guest.GUEST,
            IndexPage.INDEX_PAGE);
    }
}
