/*
 * This file is generated by jOOQ.
*/
package codes.foobar.wedapp.jooq;


import codes.foobar.wedapp.jooq.tables.Direction;
import codes.foobar.wedapp.jooq.tables.Guest;
import codes.foobar.wedapp.jooq.tables.IndexPage;
import codes.foobar.wedapp.jooq.tables.records.DirectionRecord;
import codes.foobar.wedapp.jooq.tables.records.GuestRecord;
import codes.foobar.wedapp.jooq.tables.records.IndexPageRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DirectionRecord, Integer> IDENTITY_DIRECTION = Identities0.IDENTITY_DIRECTION;
    public static final Identity<GuestRecord, Integer> IDENTITY_GUEST = Identities0.IDENTITY_GUEST;
    public static final Identity<IndexPageRecord, Integer> IDENTITY_INDEX_PAGE = Identities0.IDENTITY_INDEX_PAGE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DirectionRecord> DIRECTION_PKEY = UniqueKeys0.DIRECTION_PKEY;
    public static final UniqueKey<GuestRecord> GUEST_PKEY = UniqueKeys0.GUEST_PKEY;
    public static final UniqueKey<IndexPageRecord> INDEX_PAGE_PKEY = UniqueKeys0.INDEX_PAGE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<DirectionRecord, Integer> IDENTITY_DIRECTION = createIdentity(Direction.DIRECTION, Direction.DIRECTION.ID);
        public static Identity<GuestRecord, Integer> IDENTITY_GUEST = createIdentity(Guest.GUEST, Guest.GUEST.ID);
        public static Identity<IndexPageRecord, Integer> IDENTITY_INDEX_PAGE = createIdentity(IndexPage.INDEX_PAGE, IndexPage.INDEX_PAGE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<DirectionRecord> DIRECTION_PKEY = createUniqueKey(Direction.DIRECTION, "direction_pkey", Direction.DIRECTION.ID);
        public static final UniqueKey<GuestRecord> GUEST_PKEY = createUniqueKey(Guest.GUEST, "guest_pkey", Guest.GUEST.ID);
        public static final UniqueKey<IndexPageRecord> INDEX_PAGE_PKEY = createUniqueKey(IndexPage.INDEX_PAGE, "index_page_pkey", IndexPage.INDEX_PAGE.ID);
    }
}
