/*
 * This file is generated by jOOQ.
*/
package codes.foobar.wedapp.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>accommodation_id_seq</code>
     */
    public static final Sequence<Integer> ACCOMMODATION_ID_SEQ = new SequenceImpl<Integer>("accommodation_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>contact_id_seq</code>
     */
    public static final Sequence<Integer> CONTACT_ID_SEQ = new SequenceImpl<Integer>("contact_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>direction_id_seq</code>
     */
    public static final Sequence<Integer> DIRECTION_ID_SEQ = new SequenceImpl<Integer>("direction_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>guest_id_seq</code>
     */
    public static final Sequence<Integer> GUEST_ID_SEQ = new SequenceImpl<Integer>("guest_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>index_page_id_seq</code>
     */
    public static final Sequence<Integer> INDEX_PAGE_ID_SEQ = new SequenceImpl<Integer>("index_page_id_seq", DefaultSchema.DEFAULT_SCHEMA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
