/*
 * This file is generated by jOOQ.
*/
package codes.foobar.wedapp.jooq;


import codes.foobar.wedapp.jooq.tables.Accommodation;
import codes.foobar.wedapp.jooq.tables.Contact;
import codes.foobar.wedapp.jooq.tables.Direction;
import codes.foobar.wedapp.jooq.tables.Gift;
import codes.foobar.wedapp.jooq.tables.Guest;
import codes.foobar.wedapp.jooq.tables.IndexPage;
import codes.foobar.wedapp.jooq.tables.Role;
import codes.foobar.wedapp.jooq.tables.User;
import codes.foobar.wedapp.jooq.tables.UserRole;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>accommodation</code>.
     */
    public static final Accommodation ACCOMMODATION = codes.foobar.wedapp.jooq.tables.Accommodation.ACCOMMODATION;

    /**
     * The table <code>contact</code>.
     */
    public static final Contact CONTACT = codes.foobar.wedapp.jooq.tables.Contact.CONTACT;

    /**
     * The table <code>direction</code>.
     */
    public static final Direction DIRECTION = codes.foobar.wedapp.jooq.tables.Direction.DIRECTION;

    /**
     * The table <code>gift</code>.
     */
    public static final Gift GIFT = codes.foobar.wedapp.jooq.tables.Gift.GIFT;

    /**
     * The table <code>guest</code>.
     */
    public static final Guest GUEST = codes.foobar.wedapp.jooq.tables.Guest.GUEST;

    /**
     * The table <code>index_page</code>.
     */
    public static final IndexPage INDEX_PAGE = codes.foobar.wedapp.jooq.tables.IndexPage.INDEX_PAGE;

    /**
     * The table <code>role</code>.
     */
    public static final Role ROLE = codes.foobar.wedapp.jooq.tables.Role.ROLE;

    /**
     * The table <code>user</code>.
     */
    public static final User USER = codes.foobar.wedapp.jooq.tables.User.USER;

    /**
     * The table <code>user_role</code>.
     */
    public static final UserRole USER_ROLE = codes.foobar.wedapp.jooq.tables.UserRole.USER_ROLE;
}
