/*
 * This file is generated by jOOQ.
*/
package codes.foobar.wedapp.jooq;


import codes.foobar.wedapp.jooq.tables.Guest;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>guest</code>.
     */
    public static final Guest GUEST = codes.foobar.wedapp.jooq.tables.Guest.GUEST;
}
