/*
 * This file is generated by jOOQ.
*/
package codes.foobar.wedapp.jooq;


import codes.foobar.wedapp.jooq.tables.Direction;
import codes.foobar.wedapp.jooq.tables.Guest;
import codes.foobar.wedapp.jooq.tables.IndexPage;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>direction</code>.
     */
    public static final Direction DIRECTION = codes.foobar.wedapp.jooq.tables.Direction.DIRECTION;

    /**
     * The table <code>guest</code>.
     */
    public static final Guest GUEST = codes.foobar.wedapp.jooq.tables.Guest.GUEST;

    /**
     * The table <code>index_page</code>.
     */
    public static final IndexPage INDEX_PAGE = codes.foobar.wedapp.jooq.tables.IndexPage.INDEX_PAGE;
}
